---
title: "20200915_tidytues"
output: html_document
---

## Load libraries and data
```{r setup, include=FALSE}

library(ggplot2)
library(dplyr)
library(lme4)
library(lmerTest)
library(readr)
library(stats)
library(Hmisc)
library(corrplot)
library(tidyr)
library(statebins) 
library(tidyverse) 
library(ggplot2)   
library(ggthemes)  
library(viridis)   
library(gganimate) 
library(transformr)

## Get the Data
tuesdata <- tidytuesdayR::tt_load('2020-09-15')
tuesdata <- tidytuesdayR::tt_load(2020, week = 38)
kids <- tuesdata$kids
#Codebook: https://jrosen48.github.io/tidykids/articles/tidykids-codebook.html


```

## Data exploration 
```{r, include=TRUE, echo=TRUE, warning=FALSE}
## Descriptives
summary(kids)

kids %>% 
  group_by(state) %>% 
  summary(inf_adj_perchild)

#filtering on the states I've lived in for fun, and on types of funding 
kids2 <- kids %>% 
  filter(state=="California" |
         state=="New York" |
         state=="Minnesota") %>% 
  filter (variable == "PK12ed" |
          variable == "highered" |
          variable == "edsubs" |
          variable == "pell" |
          variable == "TANFbasic" |
          variable == "SNAP" |
          variable == "unemp")
  
#Plot funding growth by state and type of funding
ggplot(data=kids2, aes(y= inf_adj, x=year, color=variable))+
  geom_line ()+ 
  geom_point() + 
  theme_bw () +
  facet_wrap(~state) 

#Another way with all states
kids3 <- kids %>% 
    filter (variable == "PK12ed" |
          variable == "highered" |
          variable == "edsubs" |
          variable == "pell" |
          variable == "TANFbasic" |
          variable == "SNAP" |
          variable == "unemp") 

ggplot(data=kids3, aes(y= inf_adj, x=year, color=variable))+
  geom_line ()+ 
  geom_point() + 
  theme_bw () +
  facet_wrap(~state) 

```

## Exploring how much states spend on kids education using a diverging bar chart
```{r, include=true, echo=true, warning=false}
## Diverging bar charts
# https://nhsrcommunity.com/blog/diverging-bar-charts-plotting-variance-with-ggplot2/

#set theme
theme_set(theme_classic())

#filter to look at pk-12 education only
kids4 <- kids %>% 
    filter (variable == "PK12ed" )

#make zscore
kids4 <- kids4 %>% 
  mutate(zscore = (inf_adj_perchild - mean(inf_adj_perchild, na.rm=TRUE))/sd(inf_adj_perchild, na.rm=TRUE))

#get cutoff for above and below the mean
kids4$zscore_type <- ifelse(kids4$zscore < 0, "below", "above")

#make sure state is a factor
as.factor(kids4$state)

#create base plot
ggplot(kids4, aes(x=state, y=zscore, label=zscore)) +
  geom_bar(stat='identity', aes(fill=zscore_type), width=.5) + #variable as type of funding
  scale_fill_manual(name="Dollars spent",
                    labels = c("Above Average", "Below Average"),
                    values = c("above"="#00ba38", "below"="#0b8fd3")) +
  labs(subtitle="Z score (normalised) dollars per child in $1000s spent'",
       title= "Which states care more about primary education?") +
  coord_flip()

```

## Animated gif on dollars spent per year per state
```{r, include=TRUE, echo=true, warning=false}
##Animated gif
# https://github.com/winterstat/tidytuesday/blob/master/R/tt2020_wk38.R

#install.packages("tidytuesdayR")
#install.packages("statebins")

library(statebins) # maybe make plot with this
library(tidyverse) # data cleaning
library(ggthemes)  # theme_map
library(viridis)   # color palette
library(gganimate) # animate the plot
library(transformr)# needed for animation of polygons

## Extract spending on elementary and secondary education
kids_PK12ed <- kids %>% 
  filter(variable == "PK12ed")

## Create basic plot
p <- ggplot(data = kids_PK12ed, aes(state = state, fill = inf_adj_perchild, group = year)) +
  geom_statebins() +
  labs(title = "Public spending on elementary and secondary\neducation (adjusted for inflation)",
       subtitle = 'Year: {closest_state}',
       caption = "@winterstat | #TidyTuesday | Data: [tidykids] by Joshua Rosenberg",
       fill = "$1000s spent\n (per child)") +
  scale_fill_viridis(option = "D", guide = guide_colourbar(barwidth = 10)) +
  theme_statebins() +
  theme(
    plot.margin = margin(5,5,10,5),
    plot.title = element_text(size = 20, lineheight = 1.2, margin=margin(5,0,5,0)),
    plot.subtitle = element_text(size = 18, vjust = 1),
    plot.caption = element_text(size = 12, hjust = 1),
    legend.title = element_text(size = 14, hjust = 1),
    legend.text = element_text(size = 12),
    legend.margin = margin(5,0,5,0)
  )

## Add some more formatting and specify the animation
p_anim <- p + 
  theme(
    legend.position = "bottom",
    legend.justification = c(1,1)
  ) +
  transition_states(year, transition_length = 5, state_length = 30) +
  enter_fade() +
  exit_fade()

## Render the animation
animate(p_anim, start_pause = 5, end_pause = 30, fps = 5,
        type = "cairo", height = 600, width =800)

## Save the animation
anim_save("TT2020_wk38.gif")
```


